# Generated by Django 5.2.5 on 2025-12-06 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_variation_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productview',
            name='store_produ_session_71eb85_idx',
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['-viewed_at', 'session_key'], name='store_produ_viewed__bf8e0e_idx'),
        ),
    ]
