# Generated by Django 5.2.5 on 2026-01-18 10:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_description_bn_product_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerslider',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
