# Generated by Django 5.2.5 on 2026-01-18 17:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_bannerslider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerslider',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
