# Generated by Django 5.2.5 on 2025-12-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_alter_coupon_min_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusage',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
