# Generated by Django 5.2.5 on 2026-01-10 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='transaction_id',
            new_name='tran_id',
        ),
    ]
