# Generated by Django 5.2.5 on 2025-12-17 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cartitem_unique_together'),
        ('coupon', '0002_alter_coupon_min_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_usage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='coupon.couponusage'),
        ),
    ]
