# Generated by Django 5.2.5 on 2025-12-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cart_coupon_usage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon_usage',
        ),
    ]
